### ISSUE TITLE
Placeholder is truncated if textfield is pre-populated

### ISSUE THREAD

**Issue by slhodson969** [ArtSabintsev/UIFloatLabelTextField#15] opened 2015-09-09 10:41 UTC
I am experiencing an issue where if I pre-populate the textfield, the placeholder gets truncated.

![screen shot 2015-09-09 at 12 39 36 pm](https://cloud.githubusercontent.com/assets/2744879/9759773/de4fa838-56ef-11e5-9d15-29d472536c01.png)
- First name textfield was pre-populated in `viewWillAppear`
- Last name was typed in after loading

**Comment by ArtSabintsev** [comment] 2015-09-09 16:06
Hmm, that's an interesting issue. I'll look into it.

**Comment by slhodson969** [comment] 2015-09-11 10:46
Have you had chance to look into this?

**Comment by ArtSabintsev** [comment] 2015-09-11 14:08
Not yet. Could you do me a favor, and send me a quick sample project that I could work off of? It'll be easier for me to reproduce this if I have the same codebase you have.

Thanks!

**Comment by slhodson969** [comment] 2015-09-11 14:40
Okay, so I think I found out that it has something to do with the font size.

Here's a very quick and messy version: https://github.com/slhodson969/textfields-temp-repo

If you change the font size to something smaller, say 12, it seems to work fine. With a font size of 16 though, it doesn't work when the text is pre-populated (but does when you enter it manually).

**Comment by ArtSabintsev** [comment] 2015-09-11 14:41
Cool - thanks for the info. I'll take a look tonight (or over lunch), as I'm currently working on something at work.

**Comment by slhodson969** [comment] 2015-09-14 13:14
Hey,

Did you manage to work out what's going on here? I understand you have your own life going on so I fully understand if you haven't had the time.

**Comment by ArtSabintsev** [comment] 2015-09-15 15:05
Started looking at it last night, but the solution wasn't immediately obvious. Still looking into it when I get free moments, as this bug has piqued my interest, and I'd love to get it fixed ASAP.

**Comment by estebansotoara** [comment] 2015-11-10 07:46
Hi,
I got curious about the issue and checked it out, the problem was that the frame of the floatLabel wasn't being updated after the font was changed so it remains with the size calculated with the default font (boldSystem 12.0), until the pre-filled text was erased and the toggleFloatLabel: is called and the label size is recalculated in setPlaceholder: method. I added a sizeToFit in setFloatLabelFont: so it gets updated when the font changes and the issue appears to be gone.

I have a fork with the fix (https://github.com/estebansotoara/UIFloatLabelTextField/tree/fix_issue_15), I can make a PR if you want.

**Comment by ArtSabintsev** [comment] 2015-11-10 15:43
hey, @estebansotoara!

Looks good! Can you make a PR?

**Comment by ArtSabintsev** [comment] 2015-11-10 19:23
Don't worry about the PR. It's a one line fix - I'll push it now.

Thanks, @estebansotoara!

**Comment by ArtSabintsev** [comment] 2015-11-10 19:27
Fixed in v1.2.2

**Closed by ArtSabintsev** 2015-11-10 19:27 UTC

**Comment by estebansotoara** [comment] 2015-11-10 22:47
Sorry I was at work and didn't check the email in all day, I'm glad it works.

**Comment by ArtSabintsev** [comment] 2015-11-10 22:47
No problem :) I did it over my lunch break =p
